name: WINDOW CLEANER
favicon: null
layout_spectrum: 0.8437137615401298
typography_spectrum: 0.05582579132169485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6063233017921448
  lightness: 0.02341839740984142
  saturation: 0.19470580178312957
  rhythmicContrast: 0.48618696886114776
purpose: []
